### PR TITLE
Ab exclude students

### PR DESCRIPTION
**Pull request by A-Baji**
All test cases passing:
image

### CODE REVIEW

**Comment by farrukhshahzad** [comment]
Tests are passing. The 'graduationyear' is optional so only compute if available. Also key should be 'grad_year' or 'graduation_year'. We said that multi word keys will always by separated by underscore in b/w words.

**Review by farrukhshahzad — CHANGES_REQUESTED** [review]
Add a test case if 'grad_year' is not available

**Review by farrukhshahzad — COMMENTED** [review]
Try to see if key exist using `get()` function in all functions. You can update the function :

```
def get_keyword_value(key):
    return config["keywords"][key]
```

as

```
def get_keyword_value(key):
    return config["keywords"].get(key)
```

**Comment by A-Baji** [comment]
> Tests are passing. The 'graduationyear' is optional so only compute if available. Also key should be 'grad_year' or 'graduation_year'. We said that multi word keys will always by separated by underscore in b/w words.

Yes I am planning on making all input information optional except for the student's response. If the input information isn't found, then defaults will be used.

For the key I used graduationyear as one word because that's what we have in the wiki:

> cohort/class/graduation-year/graduation-semester/etc. A group of learners who are all expected to obtain the target credential by a target semester or year. RM will utilize “graduationyear” internally.

So I wasn't sure whether to use that or to stick with underscores. I'll change it.

**Review by farrukhshahzad — APPROVED** [review]
👍

**Pull request merged**
